name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nishantb06/fastlio-backend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f fastlio-backend-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name fastlio-backend-container nishantb06/fastlio-backend